apiVersion: v1
kind: Namespace
metadata:
  name: ebs-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-data-vol-mount1
  namespace: ebs-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: storage-mount-pod
  namespace: ebs-data
  labels:
    app: nfsmount
spec:
  volumes:
  - name: share-data
    persistentVolumeClaim:
      claimName: ebs-data-vol-mount1
  containers:
  - name: storage-mount-pod
    image: alpine:latest
    resources:
      requests: 
        memory: "100Mi"
        cpu: "300m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
      - sleep
      - "3600"  
    volumeMounts:
    - name: share-data
      mountPath: /opt   

