apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  namespace: wordpress-app
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        resources:
          requests:
            cpu: "300m"
            memory: "400Mi"
          limits:
            memory: "900Mi"
            cpu: "600m"
        ports:
        - containerPort: 3306
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: redhat
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          value: wpdb123
        - name: MYSQL_DATABASE
          value: wpdata      

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql-svc
  namespace: wordpress-app
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql-port

